<?php

namespace Database\Seeders;

use App\Models\Coupon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class CouponSeeder extends Seeder
{
    public function run(): void
    {
        $coupons = [
            // ==== ORDER COUPONS ====
            [
                'name' => 'Giảm 20K đơn từ 100K',
                'coupon_code' => 'ORDER20K',
                'discount_type' => 'fixed',
                'discount_amount' => 20000,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(30),
                'status' => 1,
                'max_coupon' => 50000000,
                'min_coupon' => 100000,
                'usage_limit' => 100,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 50K đơn từ 200K',
                'coupon_code' => 'ORDER50K',
                'discount_type' => 'fixed',
                'discount_amount' => 50000,
                'type' => 'order',
                'start_date' => Carbon::now()->subDay(),
                'end_date' => Carbon::now()->addDays(20),
                'status' => 1,
                'max_coupon' => 50000000,
                'min_coupon' => 200000,
                'usage_limit' => 80,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 100K đơn từ 500K',
                'coupon_code' => 'ORDER100K',
                'discount_type' => 'fixed',
                'discount_amount' => 100000,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(40),
                'status' => 1,
                'max_coupon' => 99000000,
                'min_coupon' => 500000,
                'usage_limit' => 50,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 10% tối đa 50K',
                'coupon_code' => 'ORDER10',
                'discount_type' => 'percent',
                'discount_amount' => 10,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(15),
                'status' => 1,
                'max_coupon' => 500000,
                'min_coupon' => 100000,
                'usage_limit' => 120,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 15% tối đa 150K',
                'coupon_code' => 'ORDER15',
                'discount_type' => 'percent',
                'discount_amount' => 15,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(25),
                'status' => 1,
                'max_coupon' => 150000,
                'min_coupon' => 200000,
                'usage_limit' => 70,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 20% tối đa 200K',
                'coupon_code' => 'ORDER20',
                'discount_type' => 'percent',
                'discount_amount' => 20,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(10),
                'status' => 1,
                'max_coupon' => 200000,
                'min_coupon' => 300000,
                'usage_limit' => 60,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 30% tối đa 250K',
                'coupon_code' => 'ORDER30',
                'discount_type' => 'percent',
                'discount_amount' => 30,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(7),
                'status' => 1,
                'max_coupon' => 250000,
                'min_coupon' => 400000,
                'usage_limit' => 40,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 5% tối đa 30K',
                'coupon_code' => 'ORDER5',
                'discount_type' => 'percent',
                'discount_amount' => 5,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(20),
                'status' => 1,
                'max_coupon' => 3000000,
                'min_coupon' => 80000,
                'usage_limit' => 150,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 200K đơn từ 1 triệu',
                'coupon_code' => 'ORDER200K',
                'discount_type' => 'fixed',
                'discount_amount' => 200000,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(30),
                'status' => 1,
                'max_coupon' => 20000000,
                'min_coupon' => 1000000,
                'usage_limit' => 20,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 50% tối đa 300K',
                'coupon_code' => 'ORDER50',
                'discount_type' => 'percent',
                'discount_amount' => 50,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(5),
                'status' => 1,
                'max_coupon' => 300000,
                'min_coupon' => 1000000,
                'usage_limit' => 10,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],

            // ==== SHIPPING COUPONS ====
            [
                'name' => 'Miễn phí ship tối đa 30K',
                'coupon_code' => 'SHIPFREE',
                'discount_type' => 'fixed',
                'discount_amount' => 30000,
                'type' => 'shipping',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(15),
                'status' => 1,
                'max_coupon' => 30000,
                'min_coupon' => 0,
                'usage_limit' => 100,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 20K phí ship',
                'coupon_code' => 'SHIP20K',
                'discount_type' => 'fixed',
                'discount_amount' => 20000,
                'type' => 'shipping',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(20),
                'status' => 1,
                'max_coupon' => 20000,
                'min_coupon' => 0,
                'usage_limit' => 70,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 50% phí ship tối đa 25K',
                'coupon_code' => 'SHIP50',
                'discount_type' => 'percent',
                'discount_amount' => 50,
                'type' => 'shipping',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(25),
                'status' => 1,
                'max_coupon' => 25000,
                'min_coupon' => 0,
                'usage_limit' => 60,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 10K phí ship',
                'coupon_code' => 'SHIP10K',
                'discount_type' => 'fixed',
                'discount_amount' => 10000,
                'type' => 'shipping',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(12),
                'status' => 1,
                'max_coupon' => 10000,
                'min_coupon' => 0,
                'usage_limit' => 50,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 30K phí ship',
                'coupon_code' => 'SHIP30K',
                'discount_type' => 'fixed',
                'discount_amount' => 30000,
                'type' => 'shipping',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(15),
                'status' => 1,
                'max_coupon' => 30000,
                'min_coupon' => 0,
                'usage_limit' => 60,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],

            // ==== SPECIAL / TEST CASES ====
            [
                'name' => 'Coupon đã hết hạn',
                'coupon_code' => 'EXPIRED',
                'discount_type' => 'fixed',
                'discount_amount' => 30000,
                'type' => 'order',
                'start_date' => Carbon::now()->subDays(20),
                'end_date' => Carbon::now()->subDay(),
                'status' => 2,
                'max_coupon' => 30000000,
                'min_coupon' => 100000,
                'usage_limit' => 20,
                'per_use_limit' => 1,
                'total_used' => 5,
                'user_id' => -1,
            ],
            [
                'name' => 'Coupon sắp có hiệu lực',
                'coupon_code' => 'UPCOMING',
                'discount_type' => 'percent',
                'discount_amount' => 15,
                'type' => 'order',
                'start_date' => Carbon::now()->addDays(3),
                'end_date' => Carbon::now()->addDays(20),
                'status' => 0,
                'max_coupon' => 99000000,
                'min_coupon' => 150000,
                'usage_limit' => 40,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Coupon bị vô hiệu hóa',
                'coupon_code' => 'DISABLED',
                'discount_type' => 'fixed',
                'discount_amount' => 50000,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(30),
                'status' => 0,
                'max_coupon' => 50000000,
                'min_coupon' => 200000,
                'usage_limit' => 10,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => 0,
            ],
            [
                'name' => 'Tri ân khách hàng thân thiết',
                'coupon_code' => 'LOYALTY50K',
                'discount_type' => 'fixed',
                'discount_amount' => 50000,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(60),
                'status' => 1,
                'max_coupon' => 50000000,
                'min_coupon' => 150000,
                'usage_limit' => 5,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Giảm 30K cho khách hàng mới',
                'coupon_code' => 'NEWBIE30K',
                'discount_type' => 'fixed',
                'discount_amount' => 30000,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(7),
                'status' => 1,
                'max_coupon' => 30000000,
                'min_coupon' => 100000,
                'usage_limit' => 100,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
            [
                'name' => 'Flash Sale Giảm 40%',
                'coupon_code' => 'FLASH40',
                'discount_type' => 'percent',
                'discount_amount' => 40,
                'type' => 'order',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addHours(6),
                'status' => 1,
                'max_coupon' => 50000000,
                'min_coupon' => 0,
                'usage_limit' => 20,
                'per_use_limit' => 1,
                'total_used' => 0,
                'user_id' => -1,
            ],
        ];

        foreach ($coupons as $coupon) {
            Coupon::create($coupon);
        }
    }
}
