<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Order;
use Illuminate\Support\Carbon;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        Order::insert([
            // Order 1: No discounts
            [
                'user_id' => 1,
                'product_coupon_id' => null,
                'shipping_coupon_id' => null,
                'shipping_id' => 1,
                'shipping_fee' => 20000,
                'name' => 'Nguyễn Văn A',
                'email' => 'a@example.com',
                'phone' => '0901234567',
                'address' => '123 Lê Lợi, Q1, TP.HCM',
                'city' => 'Hồ Chí Minh',
                'ward' => 'Phường Bến Nghé',
                'postcode' => '70000',
                'payment' => 'cod',
                'payment_status' => 'unpaid',
                'subtotal' => 62980000,
                'product_discount' => 0,
                'shipping_discount' => 0,
                'total' => 63000000,
                'status' => 'pending',
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => Carbon::now()->subDays(10),
            ],
            // Order 2: Product discount (GIAM50K)
            [
                'user_id' => 2,
                'product_coupon_id' => 1,
                'shipping_coupon_id' => null,
                'shipping_id' => 2,
                'shipping_fee' => 30000,
                'name' => 'Trần Thị B',
                'email' => 'b@example.com',
                'phone' => '0907654321',
                'address' => '45 Lý Thường Kiệt, Hà Nội',
                'city' => 'Hà Nội',
                'ward' => 'Hoàn Kiếm',
                'postcode' => '10000',
                'payment' => 'banking',
                'payment_status' => 'paid',
                'subtotal' => 62980000,
                'product_discount' => 50000,
                'shipping_discount' => 0,
                'total' => 63010000,
                'status' => 'shipping',
                'created_at' => Carbon::now()->subDays(9),
                'updated_at' => Carbon::now()->subDays(9),
            ],
            // Order 3: Shipping discount (SHIP20K)
            [
                'user_id' => 3,
                'product_coupon_id' => null,
                'shipping_coupon_id' => 5,
                'shipping_id' => 3,
                'shipping_fee' => 25000,
                'name' => 'Lê Văn C',
                'email' => 'c@example.com',
                'phone' => '0911223344',
                'address' => '789 Trần Hưng Đạo, Đà Nẵng',
                'city' => 'Đà Nẵng',
                'ward' => 'Hải Châu',
                'postcode' => '550000',
                'payment' => 'cod',
                'payment_status' => 'paid',
                'subtotal' => 30990000,
                'product_discount' => 0,
                'shipping_discount' => 20000,
                'total' => 30995000,
                'status' => 'completed',
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => Carbon::now()->subDays(8),
            ],
            // Order 4: Both discounts
            [
                'user_id' => 1,
                'product_coupon_id' => 2,
                'shipping_coupon_id' => 4,
                'shipping_id' => 1,
                'shipping_fee' => 30000,
                'name' => 'Phạm Thị D',
                'email' => 'd@example.com',
                'phone' => '0912345678',
                'address' => '456 Nguyễn Huệ, Q1, TP.HCM',
                'city' => 'Hồ Chí Minh',
                'ward' => 'Phường Nguyễn Thái Bình',
                'postcode' => '70000',
                'payment' => 'banking',
                'payment_status' => 'paid',
                'subtotal' => 62980000,
                'product_discount' => 20000,
                'shipping_discount' => 30000,
                'total' => 62990000,
                'status' => 'processing',
                'created_at' => Carbon::now()->subDays(7),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            // Order 5: Percentage discount (GIAM10)
            [
                'user_id' => 2,
                'product_coupon_id' => 3,
                'shipping_coupon_id' => null,
                'shipping_id' => 2,
                'shipping_fee' => 35000,
                'name' => 'Hoàng Văn E',
                'email' => 'e@example.com',
                'phone' => '0923456789',
                'address' => '789 Hai Bà Trưng, Hà Nội',
                'city' => 'Hà Nội',
                'ward' => 'Phường Lý Thái Tổ',
                'postcode' => '10000',
                'payment' => 'cod',
                'payment_status' => 'unpaid',
                'subtotal' => 30990000,
                'product_discount' => 3099000, // 10% of 30990000
                'shipping_discount' => 0,
                'total' => 27920000,
                'status' => 'pending',
                'created_at' => Carbon::now()->subDays(6),
                'updated_at' => Carbon::now()->subDays(6),
            ],
            // Order 6: No discount
            [
                'user_id' => 3,
                'product_coupon_id' => null,
                'shipping_coupon_id' => null,
                'shipping_id' => 3,
                'shipping_fee' => 20000,
                'name' => 'Vũ Thị F',
                'email' => 'f@example.com',
                'phone' => '0934567890',
                'address' => '321 Lê Duẩn, Đà Nẵng',
                'city' => 'Đà Nẵng',
                'ward' => 'Phường Thạch Thang',
                'postcode' => '550000',
                'payment' => 'banking',
                'payment_status' => 'paid',
                'subtotal' => 31990000,
                'product_discount' => 0,
                'shipping_discount' => 0,
                'total' => 32010000,
                'status' => 'shipped',
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            // Order 7: Product discount only
            [
                'user_id' => 1,
                'product_coupon_id' => 1,
                'shipping_coupon_id' => null,
                'shipping_id' => 1,
                'shipping_fee' => 25000,
                'name' => 'Đặng Văn G',
                'email' => 'g@example.com',
                'phone' => '0945678901',
                'address' => '654 Võ Văn Tần, Q3, TP.HCM',
                'city' => 'Hồ Chí Minh',
                'ward' => 'Phường 6',
                'postcode' => '70000',
                'payment' => 'cod',
                'payment_status' => 'unpaid',
                'subtotal' => 62980000,
                'product_discount' => 50000,
                'shipping_discount' => 0,
                'total' => 63005000,
                'status' => 'pending',
                'created_at' => Carbon::now()->subDays(4),
                'updated_at' => Carbon::now()->subDays(4),
            ],
            // Order 8: Shipping discount only
            [
                'user_id' => 2,
                'product_coupon_id' => null,
                'shipping_coupon_id' => 5,
                'shipping_id' => 2,
                'shipping_fee' => 30000,
                'name' => 'Bùi Thị H',
                'email' => 'h@example.com',
                'phone' => '0956789012',
                'address' => '987 Cầu Giấy, Hà Nội',
                'city' => 'Hà Nội',
                'ward' => 'Phường Dịch Vọng',
                'postcode' => '10000',
                'payment' => 'banking',
                'payment_status' => 'paid',
                'subtotal' => 31990000,
                'product_discount' => 0,
                'shipping_discount' => 20000,
                'total' => 31990000,
                'status' => 'processing',
                'created_at' => Carbon::now()->subDays(3),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            // Order 9: No discount - cancelled
            [
                'user_id' => 3,
                'product_coupon_id' => null,
                'shipping_coupon_id' => null,
                'shipping_id' => 3,
                'shipping_fee' => 15000,
                'name' => 'Lý Văn I',
                'email' => 'i@example.com',
                'phone' => '0967890123',
                'address' => '147 An Dương Vương, Đà Nẵng',
                'city' => 'Đà Nẵng',
                'ward' => 'Phường An Hải Bắc',
                'postcode' => '550000',
                'payment' => 'cod',
                'payment_status' => 'cancelled',
                'subtotal' => 30990000,
                'product_discount' => 0,
                'shipping_discount' => 0,
                'total' => 31005000,
                'status' => 'cancelled',
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            // Order 10: Both discounts
            [
                'user_id' => 1,
                'product_coupon_id' => 2,
                'shipping_coupon_id' => 4,
                'shipping_id' => 1,
                'shipping_fee' => 30000,
                'name' => 'Trịnh Thị K',
                'email' => 'k@example.com',
                'phone' => '0978901234',
                'address' => '258 Pasteur, Q1, TP.HCM',
                'city' => 'Hồ Chí Minh',
                'ward' => 'Phường Võ Thị Sáu',
                'postcode' => '70000',
                'payment' => 'banking',
                'payment_status' => 'paid',
                'subtotal' => 62980000,
                'product_discount' => 20000,
                'shipping_discount' => 30000,
                'total' => 62990000,
                'status' => 'shipped',
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            // Order 11: Product discount
            [
                'user_id' => 2,
                'product_coupon_id' => 3,
                'shipping_coupon_id' => null,
                'shipping_id' => 2,
                'shipping_fee' => 40000,
                'name' => 'Ngô Văn L',
                'email' => 'l@example.com',
                'phone' => '0989012345',
                'address' => '369 Láng Hạ, Hà Nội',
                'city' => 'Hà Nội',
                'ward' => 'Phường Láng Hạ',
                'postcode' => '10000',
                'payment' => 'cod',
                'payment_status' => 'paid',
                'subtotal' => 31490000,
                'product_discount' => 3149000, // 10% of 31490000
                'shipping_discount' => 0,
                'total' => 28380000,
                'status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
