<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'avatar' => null,
                'address' => '123 Phố Huế, Quận Hai Bà Trưng, Hà Nội',
                'email' => 'admin@example.com',
                'email_verified_at' => now(),
                'phone' => '0900000001',
                'password' => Hash::make('password'),
                'gender' => 'Nam',
                'status' => 1,
                'role' => 0,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Staff',
                'avatar' => null,
                'address' => '45 Nguyễn Huệ, Quận 1, TP.HCM',
                'email' => 'staff@example.com',
                'email_verified_at' => now(),
                'phone' => '0900000002',
                'password' => Hash::make('password'),
                'gender' => 'Nữ',
                'status' => 1,
                'role' => 1,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hoàng Vinh Khoa',
                'avatar' => null,
                'address' => '56 Bạch Đằng, Quận Hải Châu, Đà Nẵng',
                'email' => 'kenhoangkhoaghost@gmail.com',
                'email_verified_at' => now(),
                'phone' => '0900000003',
                'password' => Hash::make('password'),
                'gender' => 'Khác',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hoàng Gia Bảo',
                'avatar' => null,
                'address' => '12 Lạch Tray, Quận Ngô Quyền, Hải Phòng',
                'email' => 'hoanggiabao20032005@gmail.com',
                'email_verified_at' => now(),
                'phone' => '0900000004',
                'password' => Hash::make('password'),
                'gender' => 'Nam',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Đỗ Thanh Bình',
                'avatar' => null,
                'address' => '89 Lê Lợi, Phường Phú Hội, TP Huế',
                'email' => 'dothanhbinh18112005@gmail.com',
                'email_verified_at' => now(),
                'phone' => '0900000005',
                'password' => Hash::make('password'),
                'gender' => 'Nữ',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nguyễn Việt Hoàng',
                'avatar' => null,
                'address' => '234 Lý Tự Trọng, Quận Ninh Kiều, Cần Thơ',
                'email' => 'hoangnvph49147@gmail.com',
                'email_verified_at' => now(),
                'phone' => '0900000006',
                'password' => Hash::make('password'),
                'gender' => 'Nam',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nguyễn Đình Sơn',
                'avatar' => null,
                'address' => '67 Đại Lộ Bình Dương, P. Hiệp Thành, TP Thủ Dầu Một, Bình Dương',
                'email' => 'nguyendinhson92005@gmail.com',
                'email_verified_at' => now(),
                'phone' => '0900000007',
                'password' => Hash::make('password'),
                'gender' => 'Nữ',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nguyễn Thị Dịu',
                'avatar' => null,
                'address' => '99 Đồng Khởi, P. Tân Hiệp, TP Biên Hòa, Đồng Nai',
                'email' => 'nguyenthidiu827@gmail.com',
                'email_verified_at' => now(),
                'phone' => '0900000008',
                'password' => Hash::make('password'),
                'gender' => 'Nam',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lê Anh Toản',
                'avatar' => null,
                'address' => '45 Lê Hồng Phong, P. Thắng Tam, TP Vũng Tàu, Bà Rịa - Vũng Tàu',
                'email' => 'toanlaph49131@gmail.com',
                'email_verified_at' => now(),
                'phone' => '0900000009',
                'password' => Hash::make('password'),
                'gender' => 'Khác',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'User07',
                'avatar' => null,
                'address' => '23 Trần Phú, P. Lộc Thọ, TP Nha Trang, Khánh Hòa',
                'email' => 'user07@example.com',
                'email_verified_at' => now(),
                'phone' => '0900000010',
                'password' => Hash::make('password'),
                'gender' => 'Nam',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'User08',
                'avatar' => null,
                'address' => '150 Nguyễn Văn Cừ, P. An Khánh, Quận Ninh Kiều, Cần Thơ',
                'email' => 'user08@example.com',
                'email_verified_at' => now(),
                'phone' => '0900000011',
                'password' => Hash::make('password'),
                'gender' => 'Nữ',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'User09',
                'avatar' => null,
                'address' => '200 Lý Thường Kiệt, P. 7, Quận Tân Bình, TP.HCM',
                'email' => 'user09@example.com',
                'email_verified_at' => now(),
                'phone' => '0900000012',
                'password' => Hash::make('password'),
                'gender' => 'Nam',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'User10',
                'avatar' => null,
                'address' => '88 Hoàng Diệu, P. Bình Thuận, Quận Hải Châu, Đà Nẵng',
                'email' => 'user10@example.com',
                'email_verified_at' => now(),
                'phone' => '0900000013',
                'password' => Hash::make('password'),
                'gender' => 'Nữ',
                'status' => 1,
                'role' => 2,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Gán role Spatie cho từng user
        $admin = User::where('email', 'admin@example.com')->first();
        if ($admin) $admin->assignRole('admin');

        $staff = User::where('email', 'staff@example.com')->first();
        if ($staff) $staff->assignRole('nhân viên');

        $user = User::where('role', '2')->first();
        if ($user) $user->assignRole('người dùng');
    }
}
